locales = {
    "arabic": ["ar", "أضف الى سلة التسوق"],
    "catalan": ["ca", "Afegeix a la cistella"],
    "czech": ["cs", "Vložit do košíku"],
    "danish": ["da", "Læg i kurv"],
    "german": ["de", "In Warenkorb legen"],
    "english (gb)": ["en-gb", "Add to basket"],
    "greek": ["el", "Προσθήκη στο καλάθι"],
    "spanish": ["es", "Añadir al carrito"],
    "finnish": ["fi", "Lisää koriin"],
    "french": ["fr", "Ajouter au panier"],
    "italian": ["it", "Aggiungi al carrello"],
    "korean": ["ko", "장바구니 담기"],
    "dutch": ["nl", "Voeg aan winkelmand toe"],
    "polish": ["pl", "Dodaj do koszyka"],
    "portuguese": ["pt", "Adicionar ao carrinho"],
    "portuguese (br)": ["pt-br", "Adicionar à cesta"],
    "romanian": ["ro", "Adauga in cos"],
    "russian": ["ru", "Добавить в корзину"],
    "slovenian": ["sk", "Pridať do košíka"],
    "ukrainian": ["uk", "Додати в кошик"],
    "chinese": ["zh-hans", "Add to basket"],
}